import React from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  StatusBar, Platform,
} from 'react-native';
import { COLORS, FONTS, SPACING, RADIUS, SHADOW } from '../constants/theme';
import AudioPlayer from '../components/AudioPlayer';

export default function VoiceDetailScreen({ navigation, route }) {
  const { audioUrl, language, diseaseName, voiceScript } = route.params;
  const flag = { english: '🇬🇧', hindi: '🇮🇳', bengali: '🇧🇩' }[language?.toLowerCase()] ?? '🎙️';

  return (
    <View style={s.root}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.bg} />
      <View style={s.topBar}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={s.backBtn}>
          <Text style={s.backIcon}>←</Text>
        </TouchableOpacity>
        <Text style={s.title}>Voice Advisory</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>

        {/* Hero */}
        <View style={s.heroBadge}>
          <Text style={s.heroEmoji}>🎙️</Text>
          <Text style={s.heroTitle}>AI Voice Advisory</Text>
          <Text style={s.heroSub}>{flag}  {language?.toUpperCase() ?? 'ENGLISH'}</Text>
          <Text style={s.heroDisease}>{diseaseName ?? 'Crop Disease'}</Text>
        </View>

        {/* Player */}
        {audioUrl ? (
          <AudioPlayer url={audioUrl} language={language ?? 'english'} />
        ) : (
          <View style={s.noAudioCard}>
            <Text style={s.noAudioEmoji}>📵</Text>
            <Text style={s.noAudioTitle}>Audio Not Available</Text>
            <Text style={s.noAudioSub}>
              The voice advisory could not be loaded. This usually happens when the backend
              tunnel URL has changed. Please restart localtunnel and update the URL in api.js.
            </Text>
          </View>
        )}

        {/* Script */}
        {voiceScript ? (
          <View style={s.card}>
            <Text style={s.cardTitle}>📄  Voice Script</Text>
            <Text style={s.body}>{voiceScript}</Text>
          </View>
        ) : null}

        {/* Info */}
        <View style={[s.card, s.infoCard]}>
          <Text style={s.cardTitle}>ℹ️  About Voice Advisory</Text>
          <Text style={s.body}>
            The voice advisory is generated by an AI language model and text-to-speech engine.
            It provides a concise, spoken summary of the disease diagnosis and the top
            recommended action for the farmer to take immediately.
          </Text>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const s = StyleSheet.create({
  root:   { flex: 1, backgroundColor: COLORS.bg },
  scroll: { paddingBottom: 24 },
  topBar: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    paddingTop: Platform.OS === 'ios' ? 56 : 44,
    paddingBottom: SPACING.sm,
    borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  backBtn:  { width: 40, height: 40, justifyContent: 'center' },
  backIcon: { fontSize: 24, color: COLORS.accent },
  title:    { fontFamily: FONTS.bold, fontSize: 17, color: COLORS.textPrimary },

  heroBadge: {
    margin: SPACING.md, padding: SPACING.lg,
    backgroundColor: COLORS.bgCard, borderRadius: RADIUS.xl,
    borderWidth: 1, borderColor: COLORS.border,
    alignItems: 'center', ...SHADOW.card,
  },
  heroEmoji:   { fontSize: 48, marginBottom: 8 },
  heroTitle:   { fontFamily: FONTS.bold, fontSize: 20, color: COLORS.textPrimary, marginBottom: 4 },
  heroSub:     { fontFamily: FONTS.regular, fontSize: 13, color: COLORS.textMuted, marginBottom: 4 },
  heroDisease: { fontFamily: FONTS.extraBold, fontSize: 18, color: COLORS.accent },

  noAudioCard: {
    margin: SPACING.md, padding: SPACING.lg,
    backgroundColor: COLORS.bgCard, borderRadius: RADIUS.lg,
    borderWidth: 1, borderColor: COLORS.danger + '44',
    alignItems: 'center',
  },
  noAudioEmoji: { fontSize: 40, marginBottom: 12 },
  noAudioTitle: { fontFamily: FONTS.semiBold, fontSize: 16, color: COLORS.danger, marginBottom: 8 },
  noAudioSub:   { fontFamily: FONTS.regular, fontSize: 12, color: COLORS.textSecondary, textAlign: 'center', lineHeight: 19 },

  card: {
    marginHorizontal: SPACING.md, marginTop: SPACING.md,
    backgroundColor: COLORS.bgCard, borderRadius: RADIUS.lg,
    borderWidth: 1, borderColor: COLORS.border,
    padding: SPACING.md, ...SHADOW.card,
  },
  infoCard:  { borderColor: COLORS.accent + '33' },
  cardTitle: { fontFamily: FONTS.semiBold, fontSize: 14, color: COLORS.accent, marginBottom: 10 },
  body:      { fontFamily: FONTS.regular, fontSize: 13, color: COLORS.textSecondary, lineHeight: 21 },
});
